var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var advertisement = new Schema({
    CampaignName:{
        type:String,
        required:true
    },
  heading1:{
      type:String,
      required:true
  },
  heading2:{
    type:String,
    required:true
   },
   heading3:{
    type:String,
    required:true
   },
   discription1:{
    type:String,
    required:true
  },
  discription2:{
    type:String,
    required:true
  },
  blog_id:{
      type:String,
      required:true
  },
  user_id:{
    type:String,
    required:true
},
  tags:[String],
  address:{
    type:String,
    required:true
  },
  city:{
    type:String,
    required:true
  },  
  state:{
    type:String,
    required:true
  },
  pincode:{
    type:String,
    required:true
  },
  country:{
    type:String,
    required:true
  },
  advertise_near:{
    type:String,
    required:true
  },
  amount_per_day:{
      type:Number,
      required:true,
      min:129,
      max:2100
  },
  days:{
      type:Number,
      required:true
  },
  total_amount:{
          type: Number,
          required:true
    },
    is_approved:{
          type:Boolean,
          default:false
    },
    is_paid:{
          type: Boolean
        },
    payment_id:{
        type:String
    },
    is_start:{
        type:String
    },
    is_end:{
        type:String
    },
    is_reject:{
        type:String
    },
    is_reject_reason:{
        type:String,
        required:()=>{
            return this.is_reject;
        }
    },
    is_submitted:{
        type:String    
    },
    start_date:{
        type:Date,
        required:true
    },
    end_date:{
        type:Date,
        required:true
    }
},{timestamps:true});
module.exports = mongoose.model('GoogleAdvertisement', advertisement);
